version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/transcendence
    docker:
      - image: circleci/python:3.6.4  # primary container or the build job
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DJANGO_SECRET_KEY: test
          DJANGO_READ_DOT_ENV_FILE: True
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        environment:
          POSTGRES_USER: transcendence
          POSTGRES_DB: transcendence4
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pipenv run python manage.py test
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
