# Generated by Django 2.2.3 on 2019-10-25 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='related_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
