# Generated by Django 2.2.3 on 2019-10-23 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20191023_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', through='posts.Bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
